package gui;

import java.awt.BorderLayout;
import java.awt.GridLayout;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class PatternViewsTree extends JPanel {

	/**
	 * auto-generated by eclipse IDE
	 */
	private static final long serialVersionUID = -9052034162028232375L;
	
	public PatternViewsTree() {
		// TODO calculate this!!!
		int arbitraryDefaultHieght = 5;
		int height = arbitraryDefaultHieght;
		JPanel leftSide = new JPanel();
		leftSide.setLayout(new GridLayout(height, 1));
//		for (int i = 1; i < height; i++) {
//			leftSide.add(new JLabel(""));
//		}
		leftSide.add(new JCheckBox("[design pattern]"));
		this.add(leftSide, BorderLayout.WEST);
		
		JPanel rightSide = new JPanel();
		rightSide.setLayout(new GridLayout(height, 1));
		rightSide.add(new JLabel(""));
		for (int i = 1; i < height; i++) {
			rightSide.add(new JCheckBox("[an instance]"));
		}
		this.add(rightSide, BorderLayout.EAST);
	}
	
	
}
